social_web_app/accounts/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, MyProfileView,ProfileView

# setting app_name as accounts
app_name = 'accounts'
# declaring all the url path for accounts app
urlpatterns = [
    path(
        'register/', #signup url
        RegisterView.as_view(),
        name='accounts-register'
    ),
    path(
        'login/',
        LoginView.as_view(),
        name='accounts-login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='accounts-logout'
    ),
    path(
        'myProfile/',
        MyProfileView.as_view(),
        name='myProfile'
    ),
    path(
        'profile/',
        ProfileView.as_view(),
        name='profile-view'
    )
]

social_web_app/likes/urls.py
from django.urls import path
from .views import PostLikeView

app_name = 'likes'
urlpatterns = [
    path(
      '<int:id>/like/',
      PostLikeView.as_view(),
      name='post-likes'
    )
]

social_web_app/posts/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    # PostUpdateView,
    # PostDeleteView,
    PostLikeView,
    PostUnLikeView,
    ChangePostPrivacy,
    DeletePost
)


app_name = 'posts'
urlpatterns = [
    path(
        '',
        PostListView.as_view(),
        name='posts-list'
    ),
    # path(
    #     '<int:id>/detail/',
    #     PostDetailView.as_view(),
    #     name='posts-detail'
    # ),
    # path(
    #     '<int:id>/update/',
    #     PostUpdateView.as_view(),
    #     name='posts-update'
    # ),
    # path(
    #     '<int:id>/delete/',
    #     PostDeleteView.as_view(),
    #     name='posts-delete'
    # ),
    path(
        'likePost/',
        PostLikeView.as_view(),
        name='likePost'
    ),
    path(
        'post/unlikePost/',
        PostUnLikeView.as_view(),
        name='unlikePost'
    ),
    path(
        'changePrivacy/',
        ChangePostPrivacy.as_view(),
        name='changePrivacy'
    ),
    path(
        'deletePost/',
        DeletePost.as_view(),
        name='deletePost'
    )
]

social_web_app/social_web_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path

urlpatterns = [
    re_path(
        r'home/',
        include('pages.urls',namespace='pages')
    ),
    # path(
    #     'dev/',
    #     include('pages.urls', namespace='pages')
    # ),
    path(
        'accounts/',
        include('accounts.urls', namespace='accounts')
    ),
    path(
        'posts/',
        include('posts.urls', namespace='posts')
    ),
    path(
        'posts/',
        include('likes.urls', namespace='likes')
    ),
    path(
        'friends/',
        include('friends.urls', namespace='profiles')
    ),
    path('admin/', admin.site.urls),
]

social_web_app/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.urls import reverse
from accounts.models import User
# User = get_user_model()

# POST MANAGER
class PostManager(models.Manager):
  def get_posts(self, *args, **kwargs):
    return self.all()

  def get_post(self, post_id, *args, **kwargs):
    return get_object_or_404(self, id=post_id)

  def get_user_posts(self, owner, *args, **kwargs):
    return self.filter(owner=owner)

  def get_user_post(self, post_id, user, *args, **kwargs):
    return get_object_or_404(self, pk=post_id, owner=user)


# POST MODEL
class Post(models.Model):
  # title = models.CharField(max_length=100)
  description = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  # owner = models.ForeignKey(
  #   User,
  #   default=1,
  #   on_delete=models.CASCADE,
  #   null=True
  # )
  owner_id = models.CharField(null=False,max_length=10,default=1)
  image = models.ImageField(upload_to='images/',null=True)
  active = models.BooleanField(default=True)
  privacy = models.BooleanField(default=True)


  objects = PostManager()

  def __str__(self, *args, **kwargs):
    return self.owner_id

  def get_absolute_url(self, *args, **kwargs):
    return reverse('posts:posts-detail', kwargs={'id': self.pk})
  
  def get_delete_url(self, *args, **kwargs):
    return reverse('posts:posts-delete', kwargs={'id': self.pk})

  def get_update_url(self, *args, **kwargs):
    return reverse('posts:posts-update', kwargs={'id': self.pk})

  def get_like_url(self, *args, **kwargs):
    return reverse('likes:post-likes', kwargs={'id': self.pk})

social_web_app/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
  # title = forms.CharField(
  #   widget=forms.TextInput(
  #     attrs={
  #       'class': 'form-control form-control-lg',
  #       'placeholder': 'Enter Title'
  #     }
  #   )
  # )

  description = forms.CharField(
    widget=forms.Textarea(
      attrs={
        'class': 'form-control form-control-lg',
        'placeholder': 'Enter Description',
        'rows': 3
      }
    )
  )

  image = forms.ImageField(
    required=False,
    widget=forms.FileInput(
      attrs={
        'class': 'form-control form-control-lg',
      }
    )
  )

  class Meta:
    model = Post
    fields = ( 'description','image')

  # def clean_title(self, *args, **kwargs):
  #   title = self.cleaned_data.get('title')
  #   if not title.strip():
  #     raise forms.ValidationError('Invalid title!')
  #   else:
  #     return title

  def clean_description(self, *args, **kwargs):
    description = self.cleaned_data.get('description')
    if not description.strip():
      raise forms.ValidationError('Invalid description!')
    else:
      return description

social_web_app/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, DetailView, UpdateView, DeleteView
from django.core.files.storage import FileSystemStorage

from .models import Post
from friends.models import Friends
from accounts.models import User
from likes.models import Like
from .forms import PostForm

from datetime import datetime
# from dateutil import tz

# POST LIST VIEW
class PostListView(View):
  model = Post
  form = PostForm
  template_name = 'posts/post_list.html'
  context = {}

  def get(self, request, *args, **kwargs):
    qs = self.model.objects.filter(active=True).order_by('-created_at')
    posts=list()
    for a in qs:
      print("Privacy:",a.privacy)
      postId = a.id
      ownerId = a.owner_id
      date = datetime.strptime(a.created_at.strftime('%Y-%m-%d'), '%Y-%m-%d').date()
      time = datetime.strptime(a.created_at.strftime('%H:%M'), '%H:%M').time()
      totalLikes = Like.objects.filter(post_id=postId).count()
      is_liked = Like.objects.filter(owner_id=request.session['id'],post_id=postId).count()
      print("is_liked",is_liked)
      print("totalLikes",totalLikes)
      print(int(ownerId)==int(request.session['id']))
      if int(ownerId) == int(request.session['id']):
        owner_details = User.objects.get(id=request.session['id'])
        posts.append({"post":a,"owner":owner_details,"ownerId":int(a.owner_id),"totalLikes":totalLikes,"date":date,"time":time,"is_liked":is_liked,"sessionId":int(request.session['id'])})
      else:
        is_friend = Friends.objects.filter(active=True,requested_user=int(ownerId),received_user=int(request.session['id'])).count()
        if is_friend==0:
          is_friend = Friends.objects.filter(active=True,received_user=int(ownerId),requested_user=int(request.session['id'])).count()
        print("ownerId",int(request.session['id']))
        print("is_friend",is_friend)
        # raise SystemExit
        if is_friend != 0:
          owner_details = User.objects.get(id=a.owner_id)
          posts.append({"post":a,"owner":owner_details,"ownerId":int(a.owner_id),"totalLikes":totalLikes,"date":date,"time":time,"is_liked":is_liked,"sessionId":int(request.session['id'])})
          # print(a.owner_id)
    # raise SystemExit
    form = self.form()
    self.context['title'] = 'Posts'
    self.context['posts'] = posts
    self.context['countPosts'] = len(posts)
    self.context['form'] = form
    return render(request, self.template_name, self.context)

  def post(self, request, *args, **kwargs):
    form = self.form(request.POST)
    if form.is_valid():
      # instance = form.save(commit=False)
      # instance.owner = self.request.session['id']
      # instance.save()
      # request.FILES['image']:
      if 'image' in request.FILES:
        myfile = request.FILES['image']
        fs = FileSystemStorage()
        filename = fs.save('static/images/'+myfile.name, myfile)
        uploaded_file_url = '/'+fs.url(filename)
        # print("uploaded_file_url",uploaded_file_url)
      else:
         uploaded_file_url=''
      model = Post(description=request.POST.get('description'),owner_id=request.session['id'],image=uploaded_file_url)
      model.save()
      messages.success(request, 'Post has been added to feed!')
      return redirect('posts:posts-list')
    messages.error(request, 'Oop! Enter valid details!')
    return reverse('posts:posts-list')

class PostLikeView(View):
  def get(self, request, *args, **kwargs):
    Like(owner_id=request.session['id'],post_id=request.GET.get('id')).save()
    return redirect(reverse('posts:posts-list'))

class PostUnLikeView(View):
  def get(self, request, *args, **kwargs):
    Like.objects.filter(owner_id=request.session['id'],post_id=request.GET.get('id')).delete()
    return redirect(reverse('posts:posts-list'))


# POST DETAIL VIEW
class PostDetailView(DetailView):
  queryset = Post.objects.all()
  context_object_name = 'post'
  lookup = 'id'
  
  def get_object(self, *args, **kwargs):
    return get_object_or_404(Post, pk=self.kwargs.get(self.lookup))
  
  def get_context_data(self, *args, **kwargs):
    context = super(PostDetailView, self).get_context_data(*args, **kwargs)
    context['title'] = 'Post Detail'
    return context


# POST UPDATE VIEW
# class PostUpdateView(LoginRequiredMixin, UpdateView):
#   queryset = Post.objects.all()
#   form_class = PostForm
#   context_object_name = 'post'
#   template_name = 'posts/post_update.html'
#   lookup = 'id'

#   def get_object(self, *args, **kwargs):
#     return Post.objects.get_user_post(
#       self.kwargs.get(self.lookup),
#       self.request.user
#     )

#   def get_context_data(self, *args, **kwargs):
#     context = super(PostUpdateView, self).get_context_data(*args, **kwargs)
#     context['title'] = 'Post Update'
#     return context
  
#   def get_success_url(self, *args, **kwargs):
#     messages.success(self.request, 'Post has been updated successfully!')
#     return reverse('posts:posts-detail', kwargs={'id': self.kwargs.get(self.lookup)})


# # POST DELETE VIEW
# class PostDeleteView(LoginRequiredMixin, DeleteView):
  queryset = Post.objects.all()
  context_object_name = 'post'
  template_name = 'posts/post_delete.html'
  lookup = 'id'

  def get_object(self, *args, **kwargs):
    return Post.objects.get_user_post(
      self.kwargs.get(self.lookup),
      self.request.user
    )
  
  def get_context_data(self, *args, **kwargs):
    context = super(PostDeleteView, self).get_context_data(*args, **kwargs)
    context['title'] = 'Post Delete'
    return context

  def get_success_url(self, *args, **kwargs):
    messages.success(self.request, 'Post has been deleted!')
    return reverse('posts:posts-list')

class ChangePostPrivacy(View):
  def get(self,request,*args,**kwargs):
    if int(request.GET.get('privacy')) == 1:
      setPrivacy=True
    else:
      setPrivacy=False
    Post.objects.filter(id=int(request.GET.get('id'))).update(privacy=setPrivacy)
    return redirect(reverse('posts:posts-list'))
class DeletePost(View):
  def get(self,request,*args,**kwargs):
        Post.objects.filter(id=int(request.GET.get('id'))).update(active=False)
        return redirect(reverse('posts:posts-list'))

social_web_app/posts/templates/posts/post_create.html
 
{% extends 'base.html' %}

{% block content %}
<div class="post-list">
  <h3 class="page-heading">Cre</h3>

</div>
{% endblock content %}

social_web_app/posts/templates/posts/post_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="post-delete">
  <h3 class="page-heading">Delete Post</h3>
  <div class="card">
    <div class="card-header">
      <h5>Are you sure? You wanna delete this post?</h5>
    </div>
    <div class="card-body">
      <h4 class="card-title">{{post.title}}</h4>
      <p class="card-text">{{post.description}}</p>
      <form action="" method="POST"> {% csrf_token %}
        <button type="submit" class="btn btn-danger">Yes</button>
        <a href="{{post.get_absolute_url}}" type="button" class="btn btn-dark">No</a>
      </form>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $(".post").addClass('active');
  });
</script>
{% endblock content %}

social_web_app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="post-detail">
  <h3 class="page-heading">Post Detail</h3>
  <div class="card">
    <div class="card-header text-center">
      <h4 class="card-title m-0">{{post.title}}</h4>
    </div>
    <div class="card-body text-center">
      <div class="card-left">
        <p class="card-text">Description: {{post.description}}</p>
        <p class="card-text">Author: {{post.owner.email}}</p>
        <p class="card-text">Created At: {{post.created_at}}</p>
      </div>
      <br>
      <form action="" class="">
        {% if user.is_authenticated %}
        <a href="{{post.get_comment_create_url}}" type="button" class="btn btn-dark">Comment</a>
        {% endif %}
        {% if user.is_authenticated and post.owner == user %}
        <a href="{{post.get_update_url}}" type="button" class="btn btn-info">Edit</a>
        <a href="{{post.get_delete_url}}" type="submit" class="btn btn-danger">Delete</a>
        {% endif %}
      </form>
    </div>
    {% if post.comment_set.all %}
    <div class="card-footer">
      <div class="container">
        <h5 class="m-0">Comments</h5>
        <hr>
        {% for comment in post.comment_set.all %}
        <div class="mb-2 d-flex">
          <div>
            <span class="">{{comment.text}}</span><br>
            <small>{{comment.owner}}</small>
          </div>
          {% if comment.owner == user %}
          <form action="" class="">
            <a href="{{comment.get_update_url}}" class="btn btn-sm btn-outline-dark">Edit</a>
            <a href="{{comment.get_delete_url}}" class="btn btn-sm btn-danger">Delete</a>
          </form>
          {% endif %}
        </div>
        <hr>
        {% endfor %}
      </div>
    </div>
    {% endif %}
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $(".post").addClass('active');
  });
</script>
{% endblock content %}

social_web_app/posts/templates/posts/post_list.html
 
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<style>
.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f9f9f9;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  padding: 5px 10px;
  z-index: 999;
  font-size: 15px;
}

.dropdown:hover .dropdown-content {
  display: block;
}
a:hover{
  text-decoration: none;
}
</style>
<div class="post-list">
  <header class="page-header d-flex">
    <h3 class="page-heading">Posts Feed</h3>
    {% if request.session.id %}
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#modelId">
      New Post!
    </button>
    {% endif %}
  </header>
  <hr>
  {% if countPosts == 0 %}
  <p class="lead text-muted">No posts added yet..</p>
  {% else %}
  {% for post in posts %}
  {% if post.post != None %}
  <!-- Section: Social news card -->
<section class="my-5">

  <!-- Grid row -->
  <div class="row">
    <div class="col-md-3"></div>

    <!-- Grid column -->
    <div class="col-md-6 col-lg-4">

      <!-- Card -->
      <div class="card news-card">

        <!-- Heading-->
        <div class="card-body">
          <div class="content">
            <img src="{% static 'images/userdefault.jpg' %}"  style="width: 15%;height: 15%;" class="rounded-circle avatar-img z-depth-1-half">
            {% if post.ownerId != post.sessionId %}
              <a href="{% url 'accounts:profile-view' %}?profileId={{post.owner.id}}" style="text-decoration:none;">
              {% else %}
              <a href="{% url 'accounts:myProfile' %}" style="text-decoration:none;">
                {% endif %}
              {{post.owner.name}}</a>
           {% if post.ownerId == post.sessionId %}
            <span class="dropdown" style="float:right;font-size:30px;cursor:pointer;">...
              <div class="dropdown-content">
            {% if post.post.privacy %}
                <a href="{% url 'posts:changePrivacy' %}?privacy=0&id={{post.post.id}}">Make post public</a>
            {% else %}
                <a href="{% url 'posts:changePrivacy' %}?privacy=1&id={{post.post.id}}">Make post private</a>
            {% endif %}
                <a href="{% url 'posts:deletePost' %}?privacy=0&id={{post.post.id}}" >Delete this post</a>
                </div>
            </span>
            {% endif %}
            <div class="right-side-meta" style="margin-left: 64px;
            margin-top: -17px;
            font-size: 15px;">
            {% if post.post.privacy %}
            <img src="https://img.icons8.com/android/24/000000/user.png" title="My Friends" data-toggle="tooltip" style="cursor:pointer;width:15px;height:15px;margin-left:-15px;">
            {% else %}
            <img src="https://img.icons8.com/ios-glyphs/30/000000/globe-earth.png" title="Public" data-toggle="tooltip" style="cursor:pointer;width:15px;height:15px;margin-left:-15px;"> {% endif %} {{post.date}} at {{post.time}}</div>
            {% endif %}
          </div>
        </div>

        <!-- Card image-->
        {% if post.post.image %}
        <!-- <img class="card-img-top" src="https://mdbootstrap.com/img/Photos/Others/girl1.jpg" alt="Card image cap"> -->
        <img src="{{post.post.image}}" style="max-height:200px;"/>
        {% endif %}
        <!-- Card content -->
        <div class="card-body">

          <!-- Social meta-->
          <div class="social-meta">
            <p>{{post.post.description}}</p>
            {% if post.is_liked > 0%}
              <a href="{% url 'posts:unlikePost' %}?id={{post.post.id}}" id="unlikePost" style="cursor:pointer;font-size: 20px;">❤</a>
            {% else %}
              <a href="{% url 'posts:likePost' %}?id={{post.post.id}}" id="likePost" style="cursor:pointer;font-size: 20px;">♡</a>
             {% endif %}
              {{post.totalLikes}} likes</span>
            <!-- <p><b style="cursor:pointer;size:200%;font-size: 20px;">♡</b>13 comments</p> -->
          </div>
          <hr>
          <!-- <div class="md-form">
            <i class="far fa-heart prefix"></i>
            <input placeholder="Add Comment..." type="text" id="form5" class="form-control">
          </div> -->

        </div>

      </div>
      <!-- Card -->

    </div>
    <div class="col-md-3"></div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->

</section>
  {% endfor %}
  {% endif %}


  <!-- Modal -->
  <div class="modal fade" id="modelId" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Create Post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
          <div class="modal-body">
            {{ form|crispy }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-success">Create</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $(".post").addClass('active');
  });
          // var is_liked = "{{post.is_liked}}"
          // // console.log("is_liked","{{post.is_liked}}")
          // if(is_liked==0){
          //   $("#likePost").show()
          //   $("#unlikePost").hide()
          // }
          // else{
          //   $("#likePost").show()
          //   $("#unlikePost").hide()
          // }
          // console.log(is_liked)
          // $("#likePost").click(function(){
          //   // $.post("posts:likePost/",{},function(data){

          //   // })
          //     $.ajax({
          //       url: 'posts:likePost/',
          //       data: {
          //        id:1 
          //       },
          //       type:'post',
          //       dataType: 'json',
          //       success: function (data) {
          //         if (data.is_taken) {
          //           alert("A user with this username already exists.");
          //         }
          //       }
          //     });
          // })
          // $("#unlikePost").click(function(){
          //     $.ajax({
          //       url: '/post/unlikePost/',
          //       data: {
          //         'username': username
          //       },
          //       dataType: 'json',
          //       success: function (data) {
          //         if (data.is_taken) {
          //           alert("A user with this username already exists.");
          //         }
          //       }
          //     });
          // })
</script>
{% endblock content %}

social_web_app/posts/templates/posts/post_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="post-update">
  <h3 class="page-heading">Update Post</h3>
  <hr>
  <form action="" method="POST"> {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-lg btn-success">Update</button>
    <a href="{{post.get_absolute_url}}" class="btn btn-lg btn-dark">Discard</a>
  </form>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $(".post").addClass('active');
  });
</script>
{% endblock content %}