social_web_app/accounts/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, MyProfileView,ProfileView

# setting app_name as accounts
app_name = 'accounts'
# declaring all the url path for accounts app
urlpatterns = [
    path(
        'register/', #signup url
        RegisterView.as_view(),
        name='accounts-register'
    ),
    path(
        'login/',
        LoginView.as_view(),
        name='accounts-login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='accounts-logout'
    ),
    path(
        'myProfile/',
        MyProfileView.as_view(),
        name='myProfile'
    ),
    path(
        'profile/',
        ProfileView.as_view(),
        name='profile-view'
    )
]

social_web_app/friends/urls.py
from django.urls import path,re_path
from .views import (ProfileListView,ProfileDetailView,AllProfileListView,RemoveFriend,AddFriend,AcceptFriend,RejectFriend)

app_name = 'friends'
urlpatterns = [
    path(
        '',
        ProfileListView.as_view(),
        name='profiles-list'
    ),
    path(
        '<int:id>/detail/',
        ProfileDetailView.as_view(),
        name='profiles-detail'
    ),
    path(
        'explore-friends/',
        AllProfileListView.as_view(),
        name='explore-friends'
    ),
    re_path(
        r'^removeFriend/$',
        RemoveFriend.as_view(),
        name='removeFriend'
    ),
    re_path(
        r'^addfriend/$',
        AddFriend.as_view(),
        name='addfriend'
    ),
    re_path(
        r'^acceptfriend/$',
        AcceptFriend.as_view(),
        name='acceptfriend'
    ),
    re_path(
        r'^rejectfriend/$',
        RejectFriend.as_view(),
        name='rejectfriend'
    )#,
    # path(
    #     '<int:id>/update/',
    #     ProfileUpdateView.as_view(),
    #     name='profiles-update'
    # )
]

social_web_app/likes/urls.py
from django.urls import path
from .views import PostLikeView

app_name = 'likes'
urlpatterns = [
    path(
      '<int:id>/like/',
      PostLikeView.as_view(),
      name='post-likes'
    )
]

social_web_app/social_web_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path

urlpatterns = [
    re_path(
        r'home/',
        include('pages.urls',namespace='pages')
    ),
    # path(
    #     'dev/',
    #     include('pages.urls', namespace='pages')
    # ),
    path(
        'accounts/',
        include('accounts.urls', namespace='accounts')
    ),
    path(
        'posts/',
        include('posts.urls', namespace='posts')
    ),
    path(
        'posts/',
        include('likes.urls', namespace='likes')
    ),
    path(
        'friends/',
        include('friends.urls', namespace='profiles')
    ),
    path('admin/', admin.site.urls),
]

social_web_app/pages/templates/pages/about.html
{% extends 'base.html' %}

{% block content %}
<div class="post-list">
  <h3 class="page-heading">About</h3>
  <hr>
  <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eaque, necessitatibus voluptas doloremque expedita sunt
    incidunt magni, in pariatur aperiam unde, ad minima cumque voluptates veritatis dolores non vel tempore deleniti
    sint excepturi cupiditate? Incidunt quae magnam, quisquam accusantium odit quis!</p>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque quae, laudantium facilis assumenda minima asperiores
    culpa nemo aspernatur aut perferendis?</p>
</div>
{% endblock content %}

social_web_app/pages/templates/pages/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="post-list">
  <h3 class="page-heading">Dashboard</h3>
  <p class="lead text-muted"> Welcome {{ request.session.name }}</p>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $(".dashboard").addClass('active');
  });
</script>
{% endblock content %}

social_web_app/pages/templates/pages/home.html
{% extends 'base.html' %}

{% block content %}
<div class="post-list">
  <h3 class="page-heading">Home</h3>

</div>
{% endblock content %}

social_web_app/pages/templates/pages/myProfile.html
{% extends "base.html" %}

{% block content %}
<div class="profiles-list">
  <header class="page-header d-flex">
    <h3 class="page-heading m-0">
    {% if is_my_profile == 1 %}
      My Profile
    {% else %}
      Profile
    {% endif %}
    </h3>
  </header>
  <hr>
      <div class="card card-posts my-2">
        <div class="card-body d-flex">
          <div class="card-left">
            Name:<h3>{{myProfile.name}}</h3>
            Email:<h5>{{myProfile.email}}</h5>
            Number:<h5>{{myProfile.number}}</h5>
          </div>
          <div class="card-right">
            <!-- <a href="{{profile.get_absolute_url}}" class="btn btn-outline-primary">Accept</a>
            <a href="{{profile.get_absolute_url}}" class="btn btn-outline-primary">Reject</a> -->
            <img src="/static/images/userdefault.jpg" class="rounded-circle avatar-img z-depth-1-half">
          </div>
        </div>
      </div>
  <header class="page-header d-flex">
    {% if is_my_profile == 1 %}
    <h3 class="page-heading m-0">My Friends ({{totalFriends}})</h3>
    {% else %}
    <div class="col-sm-6">
      <h3 class="page-heading m-0">All Friends ({{totalFriends}})</h3>
    </div>
    <div class="col-sm-6">
      <h3 class="page-heading m-0">Mutual Friends ({{total_mutual}})</h3>
    </div>
    {% endif %}
  </header>
  {% if totalFriends == 0 %}
  <p class="lead text-muted">No friend found yet..</p>
  {% else %}
  {% if is_my_profile == 1 %}
  {% for profile in myFriends %}
  <div class="card card-posts my-2">
    <div class="card-body d-flex">
      <div class="card-left">
        <a href="{% url 'accounts:profile-view' %}?profileId={{profile.requestId}}" class="lead m-0" style="text-decoration:none;">{{profile.name}}</a>
      </div>
      <div class="card-right">
        <a href="{% url 'friends:removeFriend' %}?id={{profile.requestId}}" class="btn btn-outline-primary">Remove friend</a>
      </div>
    </div>
  </div>
  {% endfor %}
  {% else %}
  <div class="row">
  <div class="col-sm-6">
    {% for profile in friends %}
    <div class="card card-posts my-2">
      <div class="card-body d-flex">
        <div class="card-left">
          <a href="{% url 'accounts:profile-view' %}?profileId={{profile.friends.id}}" class="lead m-0" style="text-decoration:none;">{{profile.friends.name}}</a>
        </div>
        {% if profile.friends.id != request.session.id %}
        <div class="card-right">
          {% if  profile.is_mutual %}
            <a href="{% url 'friends:removeFriend' %}?id={{profile.friends.id}}" class="btn btn-outline-primary">Remove Friend</a>
          {% else %}
            <a href="{% url 'friends:addfriend' %}?id={{profile.friends.id}}" class="btn btn-outline-primary">Add Friend</a>
          {% endif %}
        </div>
        {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="col-sm-6">
  {% for profile in friends %}
  {% if  profile.is_mutual %}
  <div class="card card-posts my-2">
    <div class="card-body d-flex">
      <div class="card-left">
        <a href="{% url 'accounts:profile-view' %}?profileId={{profile.friends.id}}" class="lead m-0" style="text-decoration:none;">{{profile.friends.name}}</a>
      </div>
      {% if profile.friends.id != request.session.id %}
      <div class="card-right">
        {% if  profile.is_mutual %}
          <a href="{% url 'friends:removeFriend' %}?id={{profile.friends.id}}" class="btn btn-outline-primary">Remove Friend</a>
        {% else %}
          <a href="{% url 'friends:addfriend' %}?id={{profile.friends.id}}" class="btn btn-outline-primary">Add Friend</a>
        {% endif %}
      </div>
      {% endif %}
    </div>
  </div>
  {% endif %}
  {% endfor %}
  </div>

  {% endif %}
  {% endif %}
</div>
<script>
$(".myProfile").addClass('active');
</script>
{% endblock content %}