social_web_app/accounts/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, MyProfileView,ProfileView

# setting app_name as accounts
app_name = 'accounts'
# declaring all the url path for accounts app
urlpatterns = [
    path(
        'register/', #signup url
        RegisterView.as_view(),
        name='accounts-register'
    ),
    path(
        'login/',
        LoginView.as_view(),
        name='accounts-login'
    ),
    path(
        'logout/',
        LogoutView.as_view(),
        name='accounts-logout'
    ),
    path(
        'myProfile/',
        MyProfileView.as_view(),
        name='myProfile'
    ),
    path(
        'profile/',
        ProfileView.as_view(),
        name='profile-view'
    )
]

social_web_app/friends/urls.py
from django.urls import path,re_path
from .views import (ProfileListView,ProfileDetailView,AllProfileListView,RemoveFriend,AddFriend,AcceptFriend,RejectFriend)

app_name = 'friends'
urlpatterns = [
    path(
        '',
        ProfileListView.as_view(),
        name='profiles-list'
    ),
    path(
        '<int:id>/detail/',
        ProfileDetailView.as_view(),
        name='profiles-detail'
    ),
    path(
        'explore-friends/',
        AllProfileListView.as_view(),
        name='explore-friends'
    ),
    re_path(
        r'^removeFriend/$',
        RemoveFriend.as_view(),
        name='removeFriend'
    ),
    re_path(
        r'^addfriend/$',
        AddFriend.as_view(),
        name='addfriend'
    ),
    re_path(
        r'^acceptfriend/$',
        AcceptFriend.as_view(),
        name='acceptfriend'
    ),
    re_path(
        r'^rejectfriend/$',
        RejectFriend.as_view(),
        name='rejectfriend'
    )#,
    # path(
    #     '<int:id>/update/',
    #     ProfileUpdateView.as_view(),
    #     name='profiles-update'
    # )
]

social_web_app/likes/urls.py
from django.urls import path
from .views import PostLikeView

app_name = 'likes'
urlpatterns = [
    path(
      '<int:id>/like/',
      PostLikeView.as_view(),
      name='post-likes'
    )
]

social_web_app/pages/urls.py
from django.urls import path
from .views import IndexView, DashboardView, AboutView

app_name = 'pages'
urlpatterns = [
    path(
        'home/',
        IndexView.as_view(),
        name='home-view'
    ),
    path(
        'dashboard/',
        DashboardView.as_view(),
        name='dashboard-view'
    ),
    path(
        'about/',
        AboutView.as_view(),
        name='about-view'
    )
]

social_web_app/posts/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    # PostUpdateView,
    # PostDeleteView,
    PostLikeView,
    PostUnLikeView,
    ChangePostPrivacy,
    DeletePost
)


app_name = 'posts'
urlpatterns = [
    path(
        '',
        PostListView.as_view(),
        name='posts-list'
    ),
    # path(
    #     '<int:id>/detail/',
    #     PostDetailView.as_view(),
    #     name='posts-detail'
    # ),
    # path(
    #     '<int:id>/update/',
    #     PostUpdateView.as_view(),
    #     name='posts-update'
    # ),
    # path(
    #     '<int:id>/delete/',
    #     PostDeleteView.as_view(),
    #     name='posts-delete'
    # ),
    path(
        'likePost/',
        PostLikeView.as_view(),
        name='likePost'
    ),
    path(
        'post/unlikePost/',
        PostUnLikeView.as_view(),
        name='unlikePost'
    ),
    path(
        'changePrivacy/',
        ChangePostPrivacy.as_view(),
        name='changePrivacy'
    ),
    path(
        'deletePost/',
        DeletePost.as_view(),
        name='deletePost'
    )
]

social_web_app/social_web_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path

urlpatterns = [
    re_path(
        r'home/',
        include('pages.urls',namespace='pages')
    ),
    # path(
    #     'dev/',
    #     include('pages.urls', namespace='pages')
    # ),
    path(
        'accounts/',
        include('accounts.urls', namespace='accounts')
    ),
    path(
        'posts/',
        include('posts.urls', namespace='posts')
    ),
    path(
        'posts/',
        include('likes.urls', namespace='likes')
    ),
    path(
        'friends/',
        include('friends.urls', namespace='profiles')
    ),
    path('admin/', admin.site.urls),
]

social_web_app/templates/layouts/alert.html
 <div class="container mt-3">
  {% for message in messages %}
  {% if message.tags == 'error' %}
  <div class="alert alert-danger">{{message}}</div>
  {% endif %}
  {% if message.tags == 'success' %}
  <div class="alert alert-success">{{message}}</div>
  {% endif %}
  {% endfor %}
</div>

social_web_app/templates/layouts/footer.html
<hr>
<footer class="footer">
  <div class="container">
    <p class="lead text-muted text-center">
      <strong>Dev Network</strong> &copy; & All rights reserved to <strong>yashchandani98.yc@gmail.com</strong>
    </p>
  </div>
</footer>

social_web_app/templates/layouts/navbar.html
<style>
.asteriskField{
  color:red;
}
</style>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">Social Web Network</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
      aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        {% if request.session.name %}
        <!-- <li class="nav-item dashboard">
          <a class="nav-link" href="{% url 'pages:dashboard-view' %}">Dashboard</a>
        </li> -->
        {% else %}
        <li class="nav-item home">
          <a class="nav-link" href="{% url 'pages:home-view' %}">Home</a>
        </li>
        {% endif %}
        <!-- <li class="nav-item profile">
          <a class="nav-link" href="{% url 'profiles:profiles-list'%}">Profiles</a>
        </li> -->
        {% if request.session.name %}
        <li class="nav-item post">
          <a class="nav-link" href="{% url 'posts:posts-list' %}">News Feed</a>
        </li>
        {% endif %}

        {% if request.session.name %}
        <li class="nav-item myProfile">
          <a class="nav-link" href="{% url 'accounts:myProfile' %}">My Profile</a>
        </li>
        <li class="nav-item exploreFriends">
          <a class="nav-link" href="{% url 'friends:explore-friends' %}">Explore Friends</a>
        </li>
        {% endif %}


        <!-- <li class="nav-item about">
          <a class="nav-link" href="{% url 'pages:about-view' %}">About</a>
        </li> -->
      </ul>
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
        {% if request.session.name %}
        <!-- <li class="nav-item active">
          <a class="nav-link" href=""><i class="glyphicon glyphicon-user" style="color:white;"></i>{{ request.user.email }}</a>
        </li> -->
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:accounts-logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:accounts-register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:accounts-login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>


<!-- <li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-toggle="dropdown" aria-haspopup="true"
    aria-expanded="false">Dropdown</a>
  <div class="dropdown-menu" aria-labelledby="dropdownId">
    <a class="dropdown-item" href="#">Action 1</a>
    <a class="dropdown-item" href="#">Action 2</a>
  </div>
</li> -->