social_web_app/friends/urls.py
from django.urls import path,re_path
from .views import (ProfileListView,ProfileDetailView,AllProfileListView,RemoveFriend,AddFriend,AcceptFriend,RejectFriend)

app_name = 'friends'
urlpatterns = [
    path(
        '',
        ProfileListView.as_view(),
        name='profiles-list'
    ),
    path(
        '<int:id>/detail/',
        ProfileDetailView.as_view(),
        name='profiles-detail'
    ),
    path(
        'explore-friends/',
        AllProfileListView.as_view(),
        name='explore-friends'
    ),
    re_path(
        r'^removeFriend/$',
        RemoveFriend.as_view(),
        name='removeFriend'
    ),
    re_path(
        r'^addfriend/$',
        AddFriend.as_view(),
        name='addfriend'
    ),
    re_path(
        r'^acceptfriend/$',
        AcceptFriend.as_view(),
        name='acceptfriend'
    ),
    re_path(
        r'^rejectfriend/$',
        RejectFriend.as_view(),
        name='rejectfriend'
    )#,
    # path(
    #     '<int:id>/update/',
    #     ProfileUpdateView.as_view(),
    #     name='profiles-update'
    # )
]

social_web_app/likes/urls.py
from django.urls import path
from .views import PostLikeView

app_name = 'likes'
urlpatterns = [
    path(
      '<int:id>/like/',
      PostLikeView.as_view(),
      name='post-likes'
    )
]

social_web_app/social_web_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include, re_path

urlpatterns = [
    re_path(
        r'home/',
        include('pages.urls',namespace='pages')
    ),
    # path(
    #     'dev/',
    #     include('pages.urls', namespace='pages')
    # ),
    path(
        'accounts/',
        include('accounts.urls', namespace='accounts')
    ),
    path(
        'posts/',
        include('posts.urls', namespace='posts')
    ),
    path(
        'posts/',
        include('likes.urls', namespace='likes')
    ),
    path(
        'friends/',
        include('friends.urls', namespace='profiles')
    ),
    path('admin/', admin.site.urls),
]

social_web_app/friends/models.py
from django.db import models

# Create your models here.
class Friends(models.Model):
    requested_user = models.IntegerField(null=False)
    received_user = models.IntegerField(null=False)
    active = models.BooleanField(default=True)
    connected_date = models.DateTimeField(auto_now_add=True)
    # request_date = models.DateTimeField(auto_now_add=True)
class FriendRequest(models.Model):
    requested_user = models.IntegerField(null=False)
    received_user = models.IntegerField(null=False)
    active = models.BooleanField(default=True)
    request_date = models.DateTimeField(auto_now_add=True)

social_web_app/friends/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse
from django.views.generic import (
  View,
  ListView,
  CreateView,
  DetailView,
  UpdateView,
  DeleteView
)

# from .models import Profile, Education, Experience, Social
from .models import (Friends,FriendRequest)
from accounts.models import User
# from .forms import ProfileForm, EducationForm, ExperienceForm, SocialForm



# PROFILE LIST VIEW
class ProfileListView(ListView):
  queryset = Friends.objects.filter()
  context_object_name = 'profiles'
  template_name = 'friends/profile_list.html'

  # def get_context_data(self, *args, **kwargs):
  #   queryset = Friends.objects.filter()
  #   context = super(ProfileListView, self).get_context_data(*args, **kwargs)
  #   context['title'] = 'Profiles'
  #   return context
  # def get_context_data(self, *args, **kwargs):
  #   queryset = User.objects.filter()
  #   context = super(ProfileListView, self).get_context_data(*args, **kwargs)
  #   context['title'] = 'Profiles'
  #   return context
  def get(self,request,*args, **kwargs):
    queryset = Friends.objects.filter(received_user=request.session.get('id'))
    print("queryset",queryset)
    myFriends = list()
    for friends in queryset:
      requestedUser = User.objects.get(id=friends.requested_user)
      # print(requestedUser.id)
      # requestedUser = User.objects.filter(id=friends.requested_user)
      friendsDetail={'id':requestedUser.id,'name':requestedUser.name}
      myFriends.append(friendsDetail)
      print("queryset",myFriends)
    return render(request, 'friends/profile_list.html', {"title":'My Friends',"profiles":queryset})


class AllProfileListView(ListView):
  queryset = Friends.objects.filter()
  context_object_name = 'profiles'
  template_name = 'profiles/profile_list.html'

  def get(self,request,*args, **kwargs):
    friendRequests = FriendRequest.objects.filter(received_user=request.session.get('id'),active=True)
    totalRequests=list()
    for requests in friendRequests:
      userRequest = User.objects.get(id=requests.requested_user)
      friendsDetail={'id':userRequest.id,'name':userRequest.name,'requested_user':requests.requested_user}
      totalRequests.append(friendsDetail)
    allUsers = User.objects.filter(active=True)
    return render(request, 'friends/profile_list.html', {"title":'Explore Friends',"allUsers":allUsers,"friendRequests":totalRequests,"totalRequests":len(totalRequests)})

class RemoveFriend(View):
  def get(self,request,*args, **kwargs):
    Friends.objects.filter(id=request.GET.get('id')).update(active=False)
    print(request.GET.get('id'))
    return redirect(reverse('accounts:myProfile'))


class AddFriend(View):
  def get(self,request,*args, **kwargs):
    request = FriendRequest(requested_user=request.session['id'],received_user=request.GET.get('id'))
    request.save()
    return redirect(reverse('friends:profiles-list'))

class AcceptFriend(View):
  def get(self,request,*args, **kwargs):
        FriendRequest.objects.filter(requested_user=request.GET.get('id'),received_user=request.session['id']).update(active=False)
        friend_new = Friends(requested_user=request.GET.get('id'),received_user=request.session['id'])
        friend_new.save()
        return redirect(reverse('friends:profiles-list'))

class RejectFriend(View):
  def get(self,request,*args, **kwargs):
        FriendRequest.objects.filter(requested_user=request.GET.get('id'),received_user=request.session['id']).update(active=False)
        # friend_new = Friends(requested_user=request.GET.get('id'),received_user=request.session['id'])
        # friend_new.save()
        return redirect(reverse('friends:profiles-list'))

# PROFILE CREATE VIEW
# class ProfileCreateView(LoginRequiredMixin, CheckAuthProfileMixin, CreateView):
#   queryset = Profile.objects.all()
#   template_name = 'friends/profile_create.html'
#   form_class = ProfileForm

#   def form_valid(self, form):
#     form.instance.user = self.request.user
#     messages.success(self.request, 'Profile has been created successfully!')
#     return super(ProfileCreateView, self).form_valid(form)

#   def get_context_data(self, *args, **kwargs):
#     context = super(ProfileCreateView, self).get_context_data(*args, **kwargs)
    
#     if self.get_object() is None:
#       context['title'] = 'Create Profile'
#       return context
#     else:
#       context['title'] = 'Create Profile'
#       context['profile'] = self.get_object()
#       return context


# # PROFILE DETAIL VIEW
class ProfileDetailView(LoginRequiredMixin, DetailView):
  queryset = Friends.objects.all()
  context_object_name = 'profile'

  def get_object(self, *args, **kwargs):
    return get_object_or_404(
      Profile,
      pk=self.kwargs.get('id')
    )

  def get_context_data(self, *args, **kwargs):
    context = super(ProfileDetailView, self).get_context_data(*args, **kwargs)
    context['title'] = self.get_object().name
    return context

social_web_app/friends/templates/friends/profile_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="profiles-create" style="width: 60%; margin:auto">
  <header class="page-header d-flex">
    <h3 class="page-heading">Create Profile</h3>
  </header>
  <hr>
  {% if profile %}
  <p class="lead">You already have a profile</p>
  <a href="{% url 'profiles:profiles-detail' id=profile.pk %}" class="btn btn-lg btn-primary">Check My Profile</a>
  {% else %}
  <div class="profile-create-form">
    <form action="" method="POST"> {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-success btn-lg">CREATE PROFILE</button>
    </form>
  </div>
  {% endif %}
</div>
{% endblock content %}

social_web_app/friends/templates/friends/profile_delete.html
{% extends "base.html" %}

{% block content %}
<div class="profiles-delete">
  <header class="page-header d-flex">
    <h3 class="page-heading text-muted">Privacy Zone</h3>
  </header>
  <hr>
  <div class="card border-danger">
    <div class="card-header">
      <h4><a style="text-decoration: none;" href="{{profile.get_absolute_url}}">{{profile.name}}</a></h4>
    </div>
    <div class="card-body">
      <p class="lead">Do you wanna delete the profile?</p>
      <form action="" method="POST">{% csrf_token %}
        <div class="btn-group">
          <button type="submit" class="btn btn-danger">YES</button>
          <a href="{{profile.get_absolute_url}}" class="btn btn-dark">NO</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

social_web_app/friends/templates/friends/profile_list.html
{% extends "base.html" %}

{% block content %}
<div class="profiles-list">
  <header class="page-header d-flex">
    <h3 class="page-heading m-0">Requests</h3>
  </header>
  <hr>
  {% if totalRequests > 0 %}
    {% for requests in friendRequests %}
      <div class="card card-posts my-2">
        <div class="card-body d-flex">
          <div class="card-left">
            <p class="lead m-0">{{requests.name}}</p>
          </div>
          <div class="card-right">
            <a href="{% url 'friends:acceptfriend' %}?id={{requests.requested_user}}" class="btn btn-outline-primary">Accept</a>
            <a href="{% url 'friends:rejectfriend' %}?id={{requests.requested_user}}" class="btn btn-outline-primary">Reject</a>
          </div>
        </div>
      </div>
    {% endfor %}
  {% else %}
  <p class="lead text-muted">No friend requests found yet..</p>
  <header class="page-header d-flex">
    <h3 class="page-heading m-0">Explore</h3>
  </header>
  {% for profile in allUsers %}
    {% if profile.id != request.session.id %}
  <div class="card card-posts my-2">
    <div class="card-body d-flex">
      <div class="card-left">
        <p class="lead m-0">{{profile.name}}</p>
      </div>
      <div class="card-right">
        <a href="{% url 'friends:addfriend' %}?id={{profile.id}}" class="btn btn-outline-primary">Add friend</a>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
</div>
<script>
$(".exploreFriends").addClass('active')
</script>
{% endblock content %}